create table tb_genre (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_movie (id int8 generated by default as identity, img_url varchar(255), subtitle varchar(255), synopsis TEXT, title varchar(255), year int4, movie_genre int8, primary key (id));
create table tb_review (id int8 generated by default as identity, text varchar(255), movie_review int8, user_review int8, primary key (id));
create table tb_role (id int8 generated by default as identity, authority varchar(255), primary key (id));
create table tb_user (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table if exists tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
alter table if exists tb_movie add constraint FKsfn4ogq1r52o0760383fv6ywv foreign key (movie_genre) references tb_genre;
alter table if exists tb_review add constraint FKoxbd9vwskfjfmm7tku7w9nh17 foreign key (movie_review) references tb_movie;
alter table if exists tb_review add constraint FKnhuwwsr2shcn93jkkb5bhcl6o foreign key (user_review) references tb_user;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO TB_ROLE (AUTHORITY) VALUES ('ROLE_VISITOR');
INSERT INTO TB_ROLE (AUTHORITY) VALUES ('ROLE_MEMBER');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Ana Azure', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('Carlos Crimson', 'carlos@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO TB_USER (NAME, EMAIL, PASSWORD) VALUES ('John Doe', 'john@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 2);
INSERT INTO TB_GENRE (NAME) VALUES ('Ação');
INSERT INTO TB_GENRE (NAME) VALUES ('Drama');
INSERT INTO TB_GENRE (NAME) VALUES ('Aventura');
INSERT INTO TB_GENRE (NAME) VALUES ('Fantasia');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Vingadores: ', 'Ultimato', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg', 'Após os eventos devastadores de "Vingadores: Guerra Infinita", o universo está em ruínas devido aos esforços do Titã Louco, Thanos. Com a ajuda de aliados remanescentes, os Vingadores devem se reunir mais uma vez a fim de desfazer as ações de Thanos e restaurar a ordem no universo de uma vez por todas, não importando as consequências.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'SCOOBY!: ', 'O Filme', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg', 'Scooby e a gangue enfrentam seu mistério mais desafiador de todos os tempos: um plano para libertar o cão fantasma Cerberus no mundo. Enquanto eles correm para parar esse caopocalypse, a gangue descobre que Scooby tem um destino épico maior do que se imaginava.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'O Poderoso Chefão', '', 1972, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/AbgEQO2mneCSOc8CSnOMa8pBS8I.jpg', 'Uma família mafiosa luta para estabelecer sua supremacia nos Estados Unidos depois da Segunda Guerra Mundial. Uma tentativa de assassinato deixa o chefão Vito Corleone incapacitado e força os filhos Michael e Sonny a assumir os negócios.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'O Rei Leão', '', 1994, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/3vSpvbyxkjtMSkVvl7gadIspQR4.jpg', 'Mufasa, o Rei Leão, e a rainha Sarabi apresentam ao reino o herdeiro do trono, Simba. O recém-nascido recebe a bênção do sábio babuíno Rafiki, mas ao crescer é envolvido nas artimanhas de seu tio Scar, o invejoso e maquiavélico irmão de Mufasa, que planeja livrar-se do sobrinho e herdar o trono.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (3, 'Manual de Caça a Monstros', '', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/ezLKohe4HKsHQbwQwhv0ARo83NC.jpg', 'Recrutada por uma sociedade secreta de babás, uma adolescente enfrenta o Bicho-Papão e os monstros que sequestram um garotinho no Halloween.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (3, 'Mulan', '', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/qAKvUu2FSaDlnqznY4VOp5PmjIF.jpg', 'Hua Mulan é a espirituosa e determinada filha mais velha de um honrado guerreiro. Quando o Imperador da China emite um decreto que um homem de cada família deve servir no exército imperial, Mulan decide tomar o lugar de seu pai, que está doente. Assumindo a identidade de Hua Jun, ela se disfarça de homem para combater os invasores que estão atacando sua nação, provando-se uma grande guerreira.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Demon Slayer: ', 'O Trem Infinito', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/d1sVANghKKMZNvqjW0V6y1ejvV9.jpg', 'Tanjiro Kamado, junto com Inosuke Hashibira, um garoto criado por javalis que usa uma cabeça de javali, e Zenitsu Agatsuma, um garoto assustado que revela seu verdadeiro poder quando dorme, embarca no Trem Infinito em uma nova missão com o Hashira de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado o povo e matado os caçadores de oni que se opõem a ele!');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Arthur and Merlin: ', 'Knights of Camelot', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/jRp9gWTqVixyfUAncW4vZm2qZZZ.jpg', 'King Arthur returns home after fighting the Roman Empire. His illegitimate son has corrupted the throne of Camelot and King Arthur must reunite with the wizard Merlin and the Knights of the Round Table to fight to get back his crown.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Aves de Rapina: ', 'Arlequina e sua Emancipação Fabulosa', 2020, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg', 'Arlequina, Canário Negro, Caçadora, Cassandra Cain e a policial Renée Montoya formam um grupo inusitado de heroínas. Quando um perigoso criminoso começa a causar destruição em Gotham, as cinco mulheres precisam se unir para defender a cidade.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'X-Men: ', 'Apocalipse', 2016, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/2ex2beZ4ssMeOduLD0ILzXKCiep.jpg', 'Apocalipse, o primeiro mutante de todos, consegue retornar à vida após milhares de anos. Agora, ele sai à procura de seguidores para dominar o mundo. Caberá aos X-Men se unirem para impedir os planos do vilão e evitar uma catástofre mundial.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'Homem-Aranha ', 'no Aranhaverso', 2018, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg', 'Miles Morales é um jovem negro do Brooklyn que se tornou o Homem-Aranha inspirado no legado de Peter Parker, já falecido. Entretanto, ao visitar o túmulo de seu ídolo em uma noite chuvosa, ele é surpreendido com a presença do próprio Peter, vestindo o traje do herói aracnídeo sob um sobretudo. A surpresa fica ainda maior quando Miles descobre que ele veio de uma dimensão paralela, assim como outras variações do Homem-Aranha.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'John Wick 3: ', 'Parabellum', 2019, 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg', 'Após assassinar o chefe da máfia Santino no Hotel Continental, John Wick passa a ser perseguido pelos membros da Alta Cúpula sob a recompensa de U$14 milhões. Agora, ele precisa unir forças com antigos parceiros que o ajudaram no passado enquanto luta por sua sobrevivência.');

INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'Nova Ordem Espacial', '2092, the space sweep begins!', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/drulhSX7P5TQlEMQZ3JoXKSDEfz.jpg', 'Perseguindo detritos espaciais e sonhos distantes no ano de 2092, quatro desajustados descobrem segredos explosivos durante a tentativa de comércio de um humanoide.‎');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'Mulher-Maravilha 1984', 'Uma nova era de maravilhas começa.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/srYya1ZlI97Au4jUYAktDe3avyA.jpg', 'Em 1984, Diana Prince entra em conflito com dois inimigos formidáveis, Maxwell Lord e a Mulher-Leopardo, enquanto reencontra misteriosamente com seu antigo interesse amoroso Steve Trevor.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'Os Pequenos Vestígios', 'Há vestígios que nunca se apagam.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg', 'Um policial começa a ter problemas em sua investigação devido a seu passado obscuro e sua tendência por quebrar as regras.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Abaixo de Zero', 'Escape is not the exit.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg', 'Um ônibus penitenciário é atacado e o policial encarregado tem que enfrentar criminosos dentro e fora do veículo, além de um inimigo silencioso: o frio congelante.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Zona de Combate', 'Defiant by design.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg', 'Em um futuro próximo, um piloto de drone e um androide ultrassecreto trabalham lado a lado no campo de batalha para evitar um ataque nuclear.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'Monster Hunter', 'Junte-se à caçada.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z8TvnEVRenMSTemxYZwLGqFofgF.jpg', 'Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo. Lá, eles se envolvem em batalhas imponentes, buscando desesperadamente a sobrevivência contra bestas gigantes portadoras de habilidades surreais.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Violação', 'Nas profundezas do espaço, eles não estão sozinhos.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg', 'À beira da paternidade, um mecânico júnior a bordo de uma arca interestelar para a Nova Terra deve superar um terror cósmico malévolo com a intenção de usar a nave espacial como uma arma.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'Crocodilos: A Morte Te Espera', 'Descend into fear', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg', 'Um casal apaixonado por aventura convence seus amigos a explorar um remoto sistema de cavernas nas florestas australianas. Com uma tempestade se aproximando, eles adentram na caverna, que começa a encher, os deixando presos com um grupo de crocodilos.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (3, 'Agentes Vanguard', '', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg','A empresa de segurança secreta Vanguard é a última esperança de sobrevivência para um contador, depois que ele é alvo da organização mercenária mais mortal do mundo.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (3, 'Alerta Vermelho', '', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg','Estagnado desde 1903, a 9000 pés de altitude, um vulcão entra em erupção na Montanha Baekdu, localizada na fronteira entre a China e a Coreia do Norte. Armado com a ameaça de erupções iminentes, uma equipe de profissionais treinados exclusivamente da Coreia do Sul e do Norte se unem. Juntos, eles devem unir forças e tentar evitar um desastre catastrófico que ameaça a Península Coreana.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'Soul', 'Is all this living really worth dying for?', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg','Joe Gardner é um professor de música de ensino fundamental desanimado por não conseguir alcançar seu sonho de tocar no lendário clube de jazz The Blue Note, em Nova York. Quando um acidente o transporta para fora do seu corpo, fazendo com que ele exista em outra realidade na forma de sua alma, ele se vê forçado a embarcar em uma aventura ao lado da alma de uma criança que ainda está aprendendo sobre si, para aprender o que é necessário para retomar sua vida.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'Mortal Kombat Legends', 'A Vingança de Scorpion', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg','Após o massacre cruel de sua família pelo mercenário Sub-Zero, Hanzo Hasashi é exilado no tortuoso Netherrealm, lá, em troca de sua servidão ao sinistro Quan Chi, ele tem a chance de vingar sua família - e ressuscita como Scorpion, uma alma perdida e vingativa. De volta ao Earthrealm, Lord Raiden reúne uma equipe de guerreiros de elite - o monge Shaolin Liu Kang, a oficial das Forças Especiais Sonya Blade e o ator de ação Johnny Cage - um grupo improvável de heróis com uma chance de salvar a humanidade. Para fazer isso, eles devem derrotar a horda de gladiadores do Outworld de Shang Tsung e vencer o torneio Mortal Kombat.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Skylines', 'To save our world she must invade theirs.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg','Quando um vírus ameaça transformar os híbridos alienígenas amigáveis que agora vivem na Terra contra os humanos, a capitã Rose Corley deve liderar uma equipe de mercenários de elite em uma missão ao mundo alienígena para salvar o que resta da humanidade.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (3, 'Em busca de ''Ohana', 'Home is where ''Ohana is.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yImmxRokQ48PD49ughXdpKTAsAU.jpg','De férias no Havaí, um casal de irmãos do Brooklyn se conecta com a família e as origens enquanto buscam um tesouro perdido.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'Ponto Vermelho', '', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7KL4yJ4JsbtS1BNRilUApLvMnc5.jpg','Com o relacionamento em crise e um bebê a caminho, um casal decide passar uns dias nas montanhas para reacender a paixão, mas acaba na mira de assassinos impiedosos.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Tenet', 'O tempo acaba.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wzJRB4MKi3yK138bJyuL9nx47y6.jpg','Armado com apenas uma palavra – Tenet – e lutando pela sobrevivência do mundo inteiro, o Protagonista viaja através de um mundo crepuscular de espionagem internacional em uma missão que irá desenrolar em algo para além do tempo real.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'Ava', 'Kill. Or be killed.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/54yOImQgj8i85u9hxxnaIQBRUuo.jpg','Atormentada por dúvidas, uma assassina de elite luta para proteger a si mesma e a sua família depois que uma missão dá errado.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, '100% Lobo', 'Cada matilha precisa de um líder!', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg','Freddy Lupin, herdeiro de uma orgulhosa família de lobisomens, fica chocado quando, no seu 14º aniversário, seu primeiro "warfing" dá errado, transformando-o em um poodle feroz. Os anciões da matilha dão a Freddy até o próximo nascer da lua para provar que ele tem o coração de um lobo, ou corre o risco de ser expulso para sempre. Com a ajuda de um aliado improvável em uma rua perdida chamada Batty, Freddy deve provar que é 100% Lobo.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (4, 'Os Croods 2: Uma Nova Era', 'A sobrevivência que lute.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cjaOSjsjV6cl3uXdJqimktT880L.jpg','Os Croods 2: Uma Nova Era é uma aventura sobre uma família pré-histórica que descobre as transformações no mundo enquanto tenta permanecer unida.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Legado Explosivo', 'Nunca impeça um homem de fazer a coisa certa.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg','Um ladrão de bancos tenta se entregar porque está se apaixonando e quer viver uma vida honesta ... mas quando ele percebe que os federais são mais corruptos do que ele, ele deve lutar para limpar seu nome.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Destruição Final', 'O Último Refúgio', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg','Quando cientistas descobrem que um cometa atingirá a Terra em poucos dias e provavelmente causará a extinção da humanidade, uma família tenta cruzar o país para chegar a sua única esperança de sobrevivência: um grupo de abrigos subterrâneos em Greenland.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Bad Boys Para Sempre ', 'Sempre juntos. Até o final.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/upUy2QhMZEmtypPW3PdieKLAHxh.jpg','Armando é um assassino de sangue frio com uma natureza cruel e provocadora. Ele está comprometido com o trabalho do cartel e é enviado por sua mãe para matar Mike (Smith). Nuñez assumirá o papel de Rita, psicóloga criminal durona e engraçada que é recém-nomeada chefe da AMMO e é ex-namorada de Mike.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Bloodshot ', 'A vingança de um herói está em seu sangue', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lP5eKh8WOcPysfELrUpGhHJGZEH.jpg','Bloodshot é um ex-soldado com poderes especiais: o de regeneração e a capacidade de se metamorfosear. Assassinado ao lado da esposa, ele é ressuscitado e aprimorado com nanotecnologia, desenvolvendo tais habilidades. Ao apagarem sua memória várias vezes, ele finalmente descobre quem realmente é e parte em um busca de vingança daqueles que mataram sua família.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (1, 'Godzilla vs. Kong', 'Um dos dois cairá.', 2021, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mGJuQwMq1bEboaVTqQAK4p4zQvC.jpg','Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.');
INSERT INTO TB_MOVIE (MOVIE_GENRE, TITLE, SUBTITLE, YEAR, IMG_URL, SYNOPSIS) VALUES (2, 'Coringa', 'Coloque um sorriso nessa cara.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg','Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens em pleno metrô e os mata. Os assassinatos iniciam um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 1, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 1, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 1, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 2, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 2, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 2, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 3, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 3, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 3, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 4, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 4, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 4, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 5, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 5, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 5, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 6, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 6, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 6, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 7, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 7, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 7, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 8, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 8, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 8, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 9, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 9, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 9, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 10, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 10, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 10, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 11, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 11, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 11, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 12, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 12, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 12, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 13, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 13, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 13, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 14, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 14, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 14, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 15, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 15, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 15, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 16, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 16, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 16, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 17, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 17, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 17, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 18, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 18, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 18, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 19, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 19, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 19, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 20, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 20, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 20, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 21, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 21, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 21, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 22, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 22, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 22, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 23, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 23, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 23, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 24, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 24, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 24, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 25, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 25, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 25, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 26, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 26, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 26, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 27, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 27, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 27, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 28, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 28, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 28, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 29, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 29, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 29, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 30, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 30, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 30, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 31, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 31, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 31, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 32, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 32, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 32, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 33, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 33, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 33, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 34, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 34, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 34, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 35, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 35, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 35, 'Galera esse filme é show!! Assistam é incrível!!!');

INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 36, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 36, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 36, 'Galera esse filme é show!! Assistam é incrível!!!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 2, 37, 'Filme fantástico, recomendo muito!');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 3, 37, 'Filme legal, mas o final foi um pouco previsivel.');
INSERT INTO TB_REVIEW (USER_REVIEW, MOVIE_REVIEW, TEXT) VALUES ( 4, 37, 'Galera esse filme é show!! Assistam é incrível!!!');

